// Generated by CoffeeScript 1.4.0
(function() {
  var $, img_info_items;

  img_info_items = {
    '000_56b714ba2b1d867d41ce327b212d11c8': {
      "path": "https://lh3.googleusercontent.com/-yq4uEwge3HE/TWKEWf4rsNI/AAAAAAABUWk/wYPpRniDKwg/s800/P2210546.JPG",
      "height": 533,
      "width": 800
    },
    '001_e59aaf0246bc79a237b05088664fdd05': {
      "path": "https://lh6.googleusercontent.com/-_HO8a9cny6Q/TWKEW-_QXOI/AAAAAAABUWk/PQbniNNJWdU/s800/P2210547.JPG",
      "height": 533,
      "width": 800
    },
    '002_7240cb1eaec6e1f35245a7ab10ff1a0e': {
      "path": "https://lh3.googleusercontent.com/-otORrTXYE14/TWKEXTtj07I/AAAAAAABV2s/6CsBdCbE6YM/s800/P2210548.JPG",
      "height": 800,
      "width": 533
    },
    '003_e4e2a6e49bf26d082aa85e3474f081ff': {
      "path": "https://lh5.googleusercontent.com/-Kf4N3UZUhow/TWKEXg18CtI/AAAAAAABUWk/zP3SeeiqdAw/s800/P2210549.JPG",
      "height": 533,
      "width": 800
    },
    '004_59fd6d5e6c9442011e2946e332c55582': {
      "path": "https://lh4.googleusercontent.com/-H_302z8gj6g/TWKEY27OduI/AAAAAAABUWk/wPyxLzAplTw/s800/P2210550.JPG",
      "height": 533,
      "width": 800
    },
    '005_09d8f3c1b0302944608ca8123711aee4': {
      "path": "https://lh5.googleusercontent.com/--eN9RtI5z-4/TWKEZebNvjI/AAAAAAABUWk/sRhGkczPxJ8/s800/P2210551.JPG",
      "height": 533,
      "width": 800
    },
    '006_0e98875da676d3a4a7aa5e79f6bc6863': {
      "path": "https://lh5.googleusercontent.com/-axUqNi0od1Q/TWKEZsF8PQI/AAAAAAABUWk/NHZgdZkbDzw/s800/P2210552.JPG",
      "height": 800,
      "width": 533
    },
    '007_32168898bec74a9c6dbbf127003cc527': {
      "path": "https://lh6.googleusercontent.com/-UJtgbOYzhFs/TWKEaBZHSTI/AAAAAAABUWk/tWMk4XfzDHU/s800/P2210556.JPG",
      "height": 533,
      "width": 800
    },
    '008_48ead43d5492cd5a0b65afdd45bc4abc': {
      "path": "https://lh5.googleusercontent.com/-GkTMa1y_1Co/TWKEahZEfMI/AAAAAAABUWk/bR4g7eU_9xk/s800/P2210560.JPG",
      "height": 533,
      "width": 800
    },
    '009_5e2af9e99a23b15ce693458bc80a1847': {
      "path": "https://lh5.googleusercontent.com/-IYP2RqBK3Ec/TWKEbP9ijXI/AAAAAAABUWk/tQUO4DKjEFE/s800/P2210561.JPG",
      "height": 533,
      "width": 800
    },
    '010_a768ee939fb1c8f3f3ab0aaa098cf832': {
      "path": "https://lh4.googleusercontent.com/-XWfSp3zhNLw/TWKEbuX3JYI/AAAAAAABUWk/5OLUlDQpftA/s800/P2210562.JPG",
      "height": 533,
      "width": 800
    },
    '011_cce044264709cf9c76c34f7d78289c07': {
      "path": "https://lh5.googleusercontent.com/-nsM7G9XXaw0/TWKEbzBf0eI/AAAAAAABUWk/lrRa582vM9c/s800/P2210565.JPG",
      "height": 533,
      "width": 800
    },
    '012_8dccc63f569a03c494ca89d5b895e634': {
      "path": "https://lh6.googleusercontent.com/-6qjVqkOxET8/TWKEcT8qqZI/AAAAAAABUWk/l9VWgEWcGA8/s800/P2210566.JPG",
      "height": 533,
      "width": 800
    },
    '013_8aa3dd3a61c78fddda8944be0cae7d4b': {
      "path": "https://lh6.googleusercontent.com/-kEcSpVTTpxs/TWKEcyqw1aI/AAAAAAABUWk/_xryUnujhAE/s800/P2210567.JPG",
      "height": 533,
      "width": 800
    },
    '014_4e7f78a2a7edf1c6628e68acca34d058': {
      "path": "https://lh5.googleusercontent.com/-y_uoa5T6FrQ/TWKEdfOFfKI/AAAAAAABUWk/5QXGF4vst-s/s800/P2210568.JPG",
      "height": 800,
      "width": 533
    },
    '015_9d984b77bf7c0ab1642134ab26960af3': {
      "path": "https://lh5.googleusercontent.com/-zsrgfjbVzPU/TWKEdhm8VYI/AAAAAAABUWk/wPZI9lz52tk/s800/P2210572.JPG",
      "height": 533,
      "width": 800
    },
    '016_c745cac598a09d77c03c50477d93866f': {
      "path": "https://lh6.googleusercontent.com/-z_t7qaWInxo/TWKEeJajKhI/AAAAAAABUWk/CiUQo__ipO4/s800/P2210573.JPG",
      "height": 533,
      "width": 800
    },
    '017_8eb80151b4cc7a381db068d54c595ba9': {
      "path": "https://lh6.googleusercontent.com/-U9aaHLVB3P4/TWKEelZl4-I/AAAAAAABUWk/-knhur3p0bg/s800/P2210574.JPG",
      "height": 533,
      "width": 800
    },
    '018_770d134d59bdf53a671efdcdd43b7c91': {
      "path": "https://lh5.googleusercontent.com/-o5E1p_67ZE0/TWKEe-671KI/AAAAAAABUWk/VZJvIH7xwEo/s800/P2210575.JPG",
      "height": 800,
      "width": 533
    },
    '019_1c1c152bffc6ae68241c7ed8575e25fe': {
      "path": "https://lh6.googleusercontent.com/-vtB7n4mEdvM/TWKEfek6h8I/AAAAAAABUWk/EQn40C1I-RQ/s800/P2210576.JPG",
      "height": 533,
      "width": 800
    },
    '020_bdeb7414a0e53ac066e3059a7d82ec21': {
      "path": "https://lh5.googleusercontent.com/-_68GLbM9ZnY/TWKEfrPwlzI/AAAAAAABUWk/N7c8RcH2BP8/s800/P2210578.JPG",
      "height": 533,
      "width": 800
    },
    '021_4139fb322e030997269ab8449252f2b6': {
      "path": "https://lh5.googleusercontent.com/-srPeaGdqlW0/TWKEgHaij2I/AAAAAAABUWk/QUtIoeVZuvw/s800/P2210580.JPG",
      "height": 533,
      "width": 800
    },
    '022_8021f08edd85f2e65c083d3bd9718bf1': {
      "path": "https://lh6.googleusercontent.com/-pctA66QQtpE/TWKEgmildCI/AAAAAAABUWk/1A7YgxeGijg/s800/P2210581.JPG",
      "height": 533,
      "width": 800
    },
    '023_3b3bf289a08595242bef27906186eb0e': {
      "path": "https://lh4.googleusercontent.com/-blcXt6k0Qds/TWKEhIJdcII/AAAAAAABUWk/oUg83Ed9Otw/s800/P2210583.JPG",
      "height": 533,
      "width": 800
    },
    '024_22a1bef19a084cea6dfcdbe22b04a3e3': {
      "path": "https://lh6.googleusercontent.com/-Oxs-6NpnhuQ/TWKEhnkposI/AAAAAAABUWk/EsLYIQ4F_Kg/s800/P2210584.JPG",
      "height": 800,
      "width": 533
    },
    '025_aaef27a796b81c377bc18f33ce1ea9f3': {
      "path": "https://lh4.googleusercontent.com/-suVxqsTxR5U/TWKEh3CqG_I/AAAAAAABUWk/909wnYFlHFM/s800/P2210588.JPG",
      "height": 533,
      "width": 800
    },
    '026_3c2a0de1ac4f524b8960d0b7fa22614e': {
      "path": "https://lh3.googleusercontent.com/-xKr9xHXeCQo/TWKEiSOPKsI/AAAAAAABUWk/9UxhfLUoTFM/s800/P2210592.JPG",
      "height": 533,
      "width": 800
    },
    '027_bed3013a98ced96be92cbb029e20d138': {
      "path": "https://lh5.googleusercontent.com/-Botq4SEjc8E/TWKEi5qPJMI/AAAAAAABUWk/iUbPNzSXfyo/s800/P2210593.JPG",
      "height": 800,
      "width": 533
    },
    '028_ec9a257203ac89f89ab2b96736d68f22': {
      "path": "https://lh4.googleusercontent.com/-eAA5PNm17FI/TWKEjUf0AfI/AAAAAAABUWk/wzO_8QEpdyo/s800/P2210596.JPG",
      "height": 533,
      "width": 800
    },
    '029_5b9fa6d330e1a4b3e868f517efc157c2': {
      "path": "https://lh5.googleusercontent.com/-CsWKp3iHiD0/TWKEjt-AjGI/AAAAAAABUWk/mlREyyh9bzs/s800/P2210597.JPG",
      "height": 533,
      "width": 800
    },
    '030_0c0aec3cd7fee1f8615aaaeacd3ba770': {
      "path": "https://lh5.googleusercontent.com/-W1097C9mAJ8/TWKEkDMycKI/AAAAAAABUWk/oAxJIMmvOco/s800/P2210602.JPG",
      "height": 533,
      "width": 800
    },
    '031_4642e8be00c88fe9ba5679210bdc2790': {
      "path": "https://lh3.googleusercontent.com/-LNq3rjm0eXA/TWKEkoRi8tI/AAAAAAABUWk/hIeobdB9V5k/s800/P2210605.JPG",
      "height": 533,
      "width": 800
    },
    '032_d96c32f1ce281bd277589a40f980d96d': {
      "path": "https://lh3.googleusercontent.com/-TMU5QXMMgaI/TWKElHvYuSI/AAAAAAABUWk/2tbjzSySpO4/s800/P2210606.JPG",
      "height": 800,
      "width": 533
    },
    '033_0872e65e840f2a7a2fcc736e615c169a': {
      "path": "https://lh6.googleusercontent.com/-hMCzCjy4hVs/TWKEll71t8I/AAAAAAABUWk/EhoWS7xT8-g/s800/P2210607.JPG",
      "height": 800,
      "width": 533
    },
    '034_b17aa56133c1f5e4c01322f647371b06': {
      "path": "https://lh3.googleusercontent.com/-l_hZeHqB1_0/TWKEl2u5I1I/AAAAAAABUWk/LJHx2ejIp2E/s800/P2210608.JPG",
      "height": 533,
      "width": 800
    },
    '035_d153cacd704f98cc5f08e1b72246ab3c': {
      "path": "https://lh5.googleusercontent.com/-UXBDXNVK9VA/TWKEmdZlTgI/AAAAAAABUWk/NGU06HCPqWI/s800/P2210609.JPG",
      "height": 533,
      "width": 800
    },
    '036_50762d0e05fdf628426e7c5c3f7146d9': {
      "path": "https://lh4.googleusercontent.com/-wip2y4MDne4/TWKEmwqObEI/AAAAAAABUWk/o7f4a5XzsGg/s800/P2210614.JPG",
      "height": 533,
      "width": 800
    },
    '037_1139bf433193a0c01584dd0c134ad957': {
      "path": "https://lh3.googleusercontent.com/-LOnjTP9jLpc/TWKEnW73YaI/AAAAAAABUWk/nmrr254p3Ww/s800/P2210616.JPG",
      "height": 533,
      "width": 800
    },
    '038_511b4e3cdae4352c409c4425245d510f': {
      "path": "https://lh6.googleusercontent.com/-o2qZjWfPG94/TWKEnsZ918I/AAAAAAABUWk/ku63olkI4aM/s800/P2210617.JPG",
      "height": 800,
      "width": 533
    },
    '039_f547c61f079f5b70a475f047777811e0': {
      "path": "https://lh4.googleusercontent.com/-iU1BY4ldL7M/TWKEoKcNPHI/AAAAAAABUWk/-eloif2zP0w/s800/P2210618.JPG",
      "height": 533,
      "width": 800
    },
    '040_c7d2afa3c614fa3cc2ccd480ce837603': {
      "path": "https://lh4.googleusercontent.com/-LhD_amKr_sE/TWKEoj67ICI/AAAAAAABUWk/lyoemt68UAo/s800/P2210619.JPG",
      "height": 533,
      "width": 800
    },
    '041_db61e471ca8f9c2e0744bbf864aba526': {
      "path": "https://lh5.googleusercontent.com/-FYt9EB1iAME/TWKEpFMSXbI/AAAAAAABUWk/mvFKwbms2-8/s800/P2210620.JPG",
      "height": 533,
      "width": 800
    },
    '042_12eb12c420e456d56037a1175d0a8aac': {
      "path": "https://lh5.googleusercontent.com/-DoLPKQnBsMY/TWKEpVLNAbI/AAAAAAABUWk/rs76zqlU2uA/s800/P2210621.JPG",
      "height": 533,
      "width": 800
    },
    '043_3aec179b3614fde3860b5de90f8da703': {
      "path": "https://lh3.googleusercontent.com/-voCbpUxupTs/TWKEp3etGmI/AAAAAAABUWk/VfOwU1BSY90/s800/P2210622.JPG",
      "height": 533,
      "width": 800
    },
    '044_b3fe52eb3be4a8ce836faad707a7228b': {
      "path": "https://lh6.googleusercontent.com/-ksahQeTC49A/TWKEqJ53LWI/AAAAAAABUWk/ZcxGwnKGv9c/s800/P2210623.JPG",
      "height": 800,
      "width": 533
    },
    '045_99550aa727b52b34aad604e249d45710': {
      "path": "https://lh6.googleusercontent.com/-LokrVQ4oAdA/TWKEqkxZEpI/AAAAAAABUWk/MVuF7zJh-cY/s800/P2210624.JPG",
      "height": 533,
      "width": 800
    },
    '046_0dc42b27fcf704a60055e2717eaa8a66': {
      "path": "https://lh4.googleusercontent.com/-V01Q3oJoZuI/TWKErLXZWyI/AAAAAAABUWk/DBrXqN_mIow/s800/P2210627.JPG",
      "height": 533,
      "width": 800
    },
    '047_8e53e35b39d3f807da75acdb276f8ee6': {
      "path": "https://lh3.googleusercontent.com/-O3qSqN5_5a0/TWKErgxGa0I/AAAAAAABUWk/xQHoU2WhXfE/s800/P2210629.JPG",
      "height": 533,
      "width": 800
    },
    '048_1d2c1aa42155513a7d2c733b8f261839': {
      "path": "https://lh5.googleusercontent.com/-mg3uFEwr93c/TWKEsCr6TFI/AAAAAAABUWk/QPbidNT3DI4/s800/P2210631.JPG",
      "height": 533,
      "width": 800
    },
    '049_3a08392984e9a0e4ae65c943ec0562fe': {
      "path": "https://lh5.googleusercontent.com/-beKjNoQRsJM/TWKEsonwfZI/AAAAAAABUWk/t4Ay5w1eYjE/s800/P2210632.JPG",
      "height": 450,
      "width": 800
    },
    '050_597f02347f6cf501c29560c202c6a62b': {
      "path": "https://lh5.googleusercontent.com/-2_Ad1PpKU7I/TWKEtB6a8jI/AAAAAAABWKo/a7PeS6ac5BI/s800/P2210634.JPG",
      "height": 533,
      "width": 800
    },
    '051_32a6a10f557151c6c9109dccc0d4cccd': {
      "path": "https://lh6.googleusercontent.com/-8vrSLoE6wA4/TWKEttt9-NI/AAAAAAABUWk/LZMM-OZ7zVU/s800/P2210637.JPG",
      "height": 533,
      "width": 800
    },
    '052_c6007751b0090043148776838df08786': {
      "path": "https://lh5.googleusercontent.com/-7cY71IefJmQ/TWKEuAWycyI/AAAAAAABUWk/8p76O_9LDTQ/s800/P2210640.JPG",
      "height": 533,
      "width": 800
    },
    '053_a00af8203165522c64d504aa2103fbf9': {
      "path": "https://lh3.googleusercontent.com/-sD0ZOthh5JU/TWKEuWvL8uI/AAAAAAABUWk/K0wTm4C_Td4/s800/P2210641.JPG",
      "height": 533,
      "width": 800
    },
    '054_1d167f2b71b5e05b5f0e5be3c568a304': {
      "path": "https://lh5.googleusercontent.com/-2xooGGoikJo/TWKEu16vVyI/AAAAAAABUWk/heohBKpinn8/s800/P2210642.JPG",
      "height": 533,
      "width": 800
    },
    '055_17d559ac3113254d7a27c4cceda5401c': {
      "path": "https://lh4.googleusercontent.com/-FLbYP4DYXZg/TWKEvRtApDI/AAAAAAABUWk/Bzn6xIpA-CE/s800/P2210643.JPG",
      "height": 533,
      "width": 800
    },
    '056_1cbf835068b3e9a2358353c0f07e8761': {
      "path": "https://lh4.googleusercontent.com/-YoTK8LgO948/TWKEwWZki8I/AAAAAAABUWk/BSR_7ZCdm5k/s800/P2210646.JPG",
      "height": 800,
      "width": 600
    },
    '057_3ad336e19a4e65dea1f3bf8cc3c51a03': {
      "path": "https://lh4.googleusercontent.com/-HYAc8ao3j0Y/TWKEw8bSBXI/AAAAAAABUWk/7QMJ93F_j1w/s800/P2210648.JPG",
      "height": 533,
      "width": 800
    },
    '058_e4f3f4be440c5670c3bc4e719f59c6dd': {
      "path": "https://lh4.googleusercontent.com/-eBray0HOriM/TWKExL8R60I/AAAAAAABUaY/YvZU4_C1gsA/s800/P2210649.JPG",
      "height": 800,
      "width": 533
    },
    '059_1bdd656c580ba2cddf87b5ea523db04f': {
      "path": "https://lh4.googleusercontent.com/-hzlHwFlia5k/TWKExvFPs3I/AAAAAAABUWk/pywPexZRbyc/s800/P2210650.JPG",
      "height": 533,
      "width": 800
    },
    '060_96d496d003c5b8c9d14379c69359fab9': {
      "path": "https://lh3.googleusercontent.com/-Dhs2JC3SHqM/TWKEyCHMC8I/AAAAAAABUWk/7razCirBpLg/s800/P2210651.JPG",
      "height": 533,
      "width": 800
    },
    '061_01e71b66704a6f71c97b5cd18df8bc74': {
      "path": "https://lh3.googleusercontent.com/-gxLISKliNtM/TWKE4PZUPwI/AAAAAAABUWk/oeoLZ2uaTik/s800/P2210655.JPG",
      "height": 533,
      "width": 800
    },
    '062_b2ab27714cda040ce1c4191b76ada9d2': {
      "path": "https://lh3.googleusercontent.com/-3HsEtL8OTvU/TWKE47rh8PI/AAAAAAABUWk/Ix3iQ6X_GXw/s800/P2210656.JPG",
      "height": 533,
      "width": 800
    },
    '063_efe03c5236c5c75200813dc2e3385f12': {
      "path": "https://lh6.googleusercontent.com/-Nwyp56vOJFc/TWKE5INTypI/AAAAAAABUWk/zq2mGQnggYE/s800/P2210657.JPG",
      "height": 450,
      "width": 800
    },
    '064_bc05a3d79c96c6fbb609b4df94944cb2': {
      "path": "https://lh6.googleusercontent.com/-dFPZL9NxlPg/TWKFx9q0vNI/AAAAAAABUWk/plEyGEkydsY/s800/P2210661.jpg",
      "height": 450,
      "width": 800
    },
    '065_e81fcc92887ecf355aab3877dbeb66d0': {
      "path": "https://lh3.googleusercontent.com/-z2Vp3illX4s/TWKFyY7DAfI/AAAAAAABUWk/KyxcmftU4cw/s800/P2210664.JPG",
      "height": 533,
      "width": 800
    },
    '066_1c5659c75f518f293f9ff81f0c1bbe6e': {
      "path": "https://lh4.googleusercontent.com/-ulm1_dA4JsI/TWKFzO89neI/AAAAAAABUWk/aX4a0O4wc6U/s800/P2210684.JPG",
      "height": 533,
      "width": 800
    },
    '067_668f5995964fb966160ebe97543d577c': {
      "path": "https://lh5.googleusercontent.com/-T_u8xnLYQ2U/TWKFzzoHPQI/AAAAAAABUWk/LPa0sXzQ__k/s800/P2210689.JPG",
      "height": 533,
      "width": 800
    },
    '068_f7538f724fc32383c3e4e1e94e389c3d': {
      "path": "https://lh4.googleusercontent.com/-ug-y85H5Qxs/TWKF0axk72I/AAAAAAABUWk/7dD99o08gt8/s800/P2210692.JPG",
      "height": 533,
      "width": 800
    },
    '069_88aacd46fa6dc9287b2985c63d359756': {
      "path": "https://lh4.googleusercontent.com/-vmce_GK9Frs/TWKF0686Q-I/AAAAAAABUWk/HpcSnVPE55c/s800/P2210694.JPG",
      "height": 533,
      "width": 800
    },
    '070_987787e0b42364913f26bd60ab18a5bd': {
      "path": "https://lh5.googleusercontent.com/-dNIgzvFFPrs/TWKF1UYNVFI/AAAAAAABUWk/uIL-A-RgnF4/s800/P2210695.JPG",
      "height": 800,
      "width": 533
    },
    '071_aa0319d52571d5df7817cab78d4da772': {
      "path": "https://lh6.googleusercontent.com/-KFFxFSQ2eLU/TWKF1yP83gI/AAAAAAABUWk/1FTluB2_Vno/s800/P2210698.JPG",
      "height": 533,
      "width": 800
    },
    '072_e63aea8cecb5be292df23f00dfe98d05': {
      "path": "https://lh4.googleusercontent.com/-A5xo81ErQAg/TWKF2e8ga3I/AAAAAAABUWk/IEljgG0xRyA/s800/P2210702.JPG",
      "height": 533,
      "width": 800
    },
    '073_344a14efd49db5de3a8bf2bc7d271300': {
      "path": "https://lh3.googleusercontent.com/-FE8qhYmpm6s/TWKF26hViEI/AAAAAAABUWk/iMHi9myyNhQ/s800/P2210703.JPG",
      "height": 533,
      "width": 800
    },
    '074_a26dcaa2e858fcaf14b89e4ac171b311': {
      "path": "https://lh4.googleusercontent.com/-IwCb-LolmSU/TWKF3GwtKkI/AAAAAAABUWk/7M94IGXvx_U/s800/P2210704.JPG",
      "height": 533,
      "width": 800
    },
    '075_aa34eac855aa4c119a0073f14a360e15': {
      "path": "https://lh6.googleusercontent.com/-grfQSG9H0YA/TWKF3jy1jRI/AAAAAAABUWk/mZpAlIpCI28/s800/P2210706.JPG",
      "height": 533,
      "width": 800
    },
    '076_3669dbd93a223b82bfef8e60d52c69fa': {
      "path": "https://lh3.googleusercontent.com/-mNuXEsXFSUI/TWKF4NRoJ-I/AAAAAAABUWk/3miUK2t504k/s800/P2210708.JPG",
      "height": 800,
      "width": 533
    },
    '077_a3a42c4a54feb3722c34b8983611e8b3': {
      "path": "https://lh3.googleusercontent.com/-52rk1Ka5Bvg/TWKF4sHqqnI/AAAAAAABUWk/oazOPCXl3_0/s800/P2210711.JPG",
      "height": 533,
      "width": 800
    },
    '078_2a11e9371af9c461dd83ea16e719a4c3': {
      "path": "https://lh6.googleusercontent.com/-r8SHAURHd4g/TWKF5JDzq-I/AAAAAAABUWk/s4xNDXAzbCw/s800/P2210716.JPG",
      "height": 800,
      "width": 533
    },
    '079_f689908e4b3a961800dd8967a3d17aed': {
      "path": "https://lh5.googleusercontent.com/-G1l8xekOaNs/TWKF5hv0qTI/AAAAAAABUWk/nDOJuQfBC2w/s800/P2210717.JPG",
      "height": 533,
      "width": 800
    },
    '080_2a8636894507df90d661a3bdea131aaa': {
      "path": "https://lh4.googleusercontent.com/-Ox2hVb7lIy0/TWKF6If9etI/AAAAAAABUWk/HlfcMWZllDU/s800/P2210718.JPG",
      "height": 533,
      "width": 800
    },
    '081_c168284c36a28c33065bbd781246ef29': {
      "path": "https://lh5.googleusercontent.com/-HI5ChkQJ4sk/TWKF6lVYSnI/AAAAAAABUWk/SN3IvsW6rfI/s800/P2210719.JPG",
      "height": 533,
      "width": 800
    },
    '082_e41e570caac662cc5643254398fe1ab2': {
      "path": "https://lh6.googleusercontent.com/-cXhVUpz4zwE/TWKF6-eMtDI/AAAAAAABUWk/2wrikm4Rims/s800/P2210721.JPG",
      "height": 533,
      "width": 800
    },
    '083_95b8fa3dda9a47789fa467473b233da1': {
      "path": "https://lh5.googleusercontent.com/-Tsyn02SPLDk/TWKF7ZWhyEI/AAAAAAABUWk/NcBeqM5p5LI/s800/P2210722.JPG",
      "height": 533,
      "width": 800
    },
    '084_232a86866f76f02995c1ab8f46981697': {
      "path": "https://lh5.googleusercontent.com/-MkqoW0AHHAs/TWKF77Yjq9I/AAAAAAABUWk/SyCj4URFS6Q/s800/P2210723.JPG",
      "height": 533,
      "width": 800
    },
    '085_7b9ee3a91aa28a47b483b31afbc04a34': {
      "path": "https://lh6.googleusercontent.com/-k8Bfxn1Gr4o/TWKF8p7RvKI/AAAAAAABUWk/onbScBGzjiU/s800/P2210726.JPG",
      "height": 450,
      "width": 800
    },
    '086_ba1f9e6a8b616973184e8e2ad7caf5dc': {
      "path": "https://lh4.googleusercontent.com/-2jZ0qDKtilc/TWKF894yjdI/AAAAAAABUWk/7D2IbBbKNFA/s800/P2210730.JPG",
      "height": 800,
      "width": 533
    },
    '087_3a69a692bbac8a5a2670da953466b9a3': {
      "path": "https://lh6.googleusercontent.com/-2M_9HwzkpMc/TWKF9dR2DqI/AAAAAAABUWk/DopbWt3Da1c/s800/P2210735.JPG",
      "height": 800,
      "width": 533
    },
    '088_29e92323e52327d58829d1bb9f0cc299': {
      "path": "https://lh4.googleusercontent.com/-wAzoI0W5I0A/TWKF919mVEI/AAAAAAABUWk/N8KGhmKRx5A/s800/P2210738.JPG",
      "height": 533,
      "width": 800
    }
  };

  $ = jQuery;

  $.fn.extend({
    fixedScrollTopBar: function(option) {
      var scrolltop_bar, slowly_scroll_top;
      if (option == null) {
        option = {
          opacity: 0.7
        };
      }
      scrolltop_bar = $(this).clone();
      $(this).css("opacity", 0);
      scrolltop_bar.css("bottom", 0).css("position", "fixed").css("width", "100%").css("opacity", 0).click(slowly_scroll_top = function() {
        var current_top;
        current_top = $(window).scrollTop();
        if (current_top > 1) {
          $(window).scrollTop(Math.round(current_top / 2));
          return setTimeout(slowly_scroll_top, 50);
        } else {
          return $(window).scrollTop(0);
        }
      }).hover((function() {
        return $(this).css("opacity", 1);
      }), (function() {
        return $(this).css("opacity", option.opacity);
      }));
      $(window).scroll(function() {
        if (scrolltop_bar.css("opacity") >= 1) {
          return;
        }
        if ($(window).scrollTop() === 0 && scrolltop_bar.css("opacity") > 0) {
          return scrolltop_bar.css("opacity", 0);
        } else {
          return scrolltop_bar.css("opacity", option.opacity);
        }
      });
      return $("body").append(scrolltop_bar);
    },
    gallery: function(img_info_items, option) {
      var gallery, img_gallery, img_id, img_info;
      if (option == null) {
        option = {
          min_height: 200,
          margin: 6
        };
      }
      gallery = $(this);
      gallery.css("text-align", "center");
      img_gallery = (function() {
        var _results;
        _results = [];
        for (img_id in img_info_items) {
          img_info = img_info_items[img_id];
          gallery.append("<img id='" + img_id + "' src='" + img_info.path + "' />");
          $("#" + img_id).data("orig_width", img_info.width);
          $("#" + img_id).data("orig_height", img_info.height);
          $("#" + img_id).css("margin", option.margin / 2);
          _results.push($("#" + img_id)._setHeight(option.min_height));
        }
        return _results;
      })();
      gallery._relayout(img_info_items, option);
      return $(window).resize(function() {
        gallery.children("img").each(function() {
          return $(this)._setHeight(option.min_height);
        });
        return gallery._relayout(img_info_items, option);
      });
    },
    _setHeight: function(height) {
      var orig_height, orig_width, width;
      orig_width = $(this).data("orig_width");
      orig_height = $(this).data("orig_height");
      width = height / orig_height * orig_width;
      if (width < orig_width && height < orig_height) {
        return $(this).width(width).height(height);
      }
    },
    _resizeImage: function(ratio) {
      var current_height, current_width, new_height, new_width, orig_height, orig_width;
      orig_width = $(this).data("orig_width");
      orig_height = $(this).data("orig_height");
      current_width = $(this).width();
      current_height = $(this).height();
      new_width = current_width * ratio;
      new_height = current_height * ratio;
      if (new_width < orig_width && new_height < orig_height) {
        return $(this).width(new_width).height(new_height);
      }
    },
    _relayout: function(img_info_items, option) {
      var current_total_width, img_id, img_id_list, max_total_width, resize_ratio, row_top, rows, stretch_row;
      max_total_width = $(this).innerWidth() - 10;
      rows = {};
      $(this).children("img").each(function() {
        var top;
        top = $(this).position().top;
        if (rows[top] != null) {
          return rows[top].push($(this).attr("id"));
        } else {
          return rows[top] = [$(this).attr("id")];
        }
      });
      return stretch_row = (function() {
        var _fn, _i, _len, _results;
        _results = [];
        for (row_top in rows) {
          img_id_list = rows[row_top];
          current_total_width = 0;
          _fn = function(img_id) {
            return current_total_width += $("#" + img_id).width();
          };
          for (_i = 0, _len = img_id_list.length; _i < _len; _i++) {
            img_id = img_id_list[_i];
            _fn(img_id);
          }
          resize_ratio = (max_total_width - option.margin * (img_id_list.length - 1)) / current_total_width;
          _results.push((function() {
            var _j, _len1, _results1;
            _results1 = [];
            for (_j = 0, _len1 = img_id_list.length; _j < _len1; _j++) {
              img_id = img_id_list[_j];
              _results1.push((function(img_id) {
                return $("#" + img_id)._resizeImage(resize_ratio);
              })(img_id));
            }
            return _results1;
          })());
        }
        return _results;
      })();
    }
  });

  $(document).ready(function() {
    $("#gallery").gallery(img_info_items);
    return $("#scroll-top-bar").fixedScrollTopBar();
  });

}).call(this);
